service: chucker

plugins:
  - serverless-offline
  - serverless-offline-scheduler  

custom:
  stage: ${opt:stage, self:provider.stage}
  
provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10
  stage: develop
  environment:
    stage: ${self:custom.stage}
  iamRoleStatements:
    # Allow access to the production stage artifacts bucket
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:PutObjectAcl"
      Resource: "arn:aws:s3:::chuckstaplist.com/*"
    # Allow access to the develop stage artifacts bucket
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:PutObjectAcl"
      Resource: "arn:aws:s3:::chuckstaplist-dev/*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  chucksWebsitePoller:                   
    handler: src/lambdas/chucksProcessor/ChucksProcessorLambda.pollForUpdates
    events:
      # but upon real deploy, AWS doesn't like this: schedule: cron(* * * * * *)
      # originally, but serverless-offline-scheduler wants cron syntax
      - schedule: rate(1 minute)
      - http: GET refresh # to manually cause a refresh
  sanityChecker:
    handler: src/lambdas/sanityChecker/SanityChecker.checkSanity
    events:
      - http: GET checkSanity
